from datetime import datetime

from sqlalchemy import JSON, DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.mixins import TimestampMixin


class Candidate(Base, TimestampMixin):
    __tablename__ = "candidates"

    id: Mapped[int] = mapped_column(primary_key=True)
    full_name: Mapped[str] = mapped_column(String(255))
    # Personal/contact email — the candidate's own address, used for
    # identification and dedup on import. Never used to log in (see
    # login_email below) — see invitation_service.py.
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    phone: Mapped[str] = mapped_column(String(50), nullable=True)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=True)
    job_id: Mapped[int] = mapped_column(ForeignKey("jobs.id"))

    # System-assigned login identifier, distinct from the candidate's real
    # email above — generated by invitation_service.issue_credentials when
    # HR sends/resends an invite, together with a generated password. None
    # until the first invite is issued.
    login_email: Mapped[str] = mapped_column(String(255), unique=True, index=True, nullable=True)

    # Pre-session pipeline state (see invitation_service.py / hrStatus.ts) —
    # None/None = "Beklemede"; invited_at set = "Davet Gönderildi"; both set
    # = "Giriş Yaptı". Once an InterviewSession exists, its own status takes
    # over ("Mülakatta"/"Tamamlandı"/"Değerlendirildi").
    invited_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    first_login_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)

    skills: Mapped[list["CandidateSkill"]] = relationship(
        back_populates="candidate", cascade="all, delete-orphan"
    )
    cvs: Mapped[list["CandidateCV"]] = relationship(
        back_populates="candidate", cascade="all, delete-orphan"
    )


class CandidateSkill(Base, TimestampMixin):
    __tablename__ = "candidate_skills"

    id: Mapped[int] = mapped_column(primary_key=True)
    candidate_id: Mapped[int] = mapped_column(ForeignKey("candidates.id"))
    name: Mapped[str] = mapped_column(String(100))

    candidate: Mapped["Candidate"] = relationship(back_populates="skills")


class CandidateCV(Base, TimestampMixin):
    __tablename__ = "candidate_cvs"

    id: Mapped[int] = mapped_column(primary_key=True)
    candidate_id: Mapped[int] = mapped_column(ForeignKey("candidates.id"))
    file_path: Mapped[str] = mapped_column(String(500))
    parsed_text: Mapped[str] = mapped_column(String(10000), nullable=True)
    analysis: Mapped[dict] = mapped_column(JSON, nullable=True)

    candidate: Mapped["Candidate"] = relationship(back_populates="cvs")
