from pydantic import ValidationError
from sqlalchemy.orm import Session

from app.models.ai_score import InterviewReport
from app.models.ai_evaluation import AIEvaluation
from app.models.candidate import Candidate
from app.models.interview import CandidateAnswer, InterviewSession
from app.models.job import Job
from app.schemas.report import FinalReportLLMResponse
from app.services.ai import get_ai_provider
from app.services.ai.base import AIResponseError
from app.services.interview_service import _format_required_skills


def _format_candidate_profile(candidate: Candidate) -> str:
    skills = ", ".join(s.name for s in candidate.skills) if candidate.skills else "Not specified"
    return f"Name: {candidate.full_name}\nDeclared skills: {skills}"


def _format_questions_and_answers(session: InterviewSession) -> str:
    answers_by_question = {a.question_id: a for a in session.answers}
    blocks = []
    for question in sorted(session.questions, key=lambda q: q.order):
        answer = answers_by_question.get(question.id)
        transcript = (answer.transcript if answer else None) or "(No answer provided)"
        blocks.append(f"Q{question.order + 1}: {question.text}\nA{question.order + 1}: {transcript}")
    return "\n\n".join(blocks) if blocks else "No questions were recorded for this interview."


def _format_answer_evaluations(db: Session, answers: list[CandidateAnswer]) -> str:
    # Per-answer AIEvaluation rows only exist for interviews that went
    # through the older adaptive per-turn flow — the current fixed-
    # questions-upfront flow doesn't evaluate per answer, so this is
    # commonly empty, which is fine: the prompt says not to invent evidence.
    answer_ids = [a.id for a in answers]
    if not answer_ids:
        return "No prior AI evaluations are available for this interview."
    evaluations = db.query(AIEvaluation).filter(AIEvaluation.answer_id.in_(answer_ids)).all()
    if not evaluations:
        return "No prior AI evaluations are available for this interview."
    lines = [
        f"- Competency: {e.competency or 'N/A'}; Score: {e.score if e.score is not None else 'N/A'}; "
        f"Feedback: {e.feedback or 'N/A'}"
        for e in evaluations
    ]
    return "\n".join(lines)


def generate_final_report(db: Session, session_id: int) -> InterviewReport:
    session = db.get(InterviewSession, session_id)
    if session is None:
        raise ValueError("Interview session not found")
    if session.status == "in_progress":
        raise ValueError("Candidate has not finished this interview yet")

    existing = db.query(InterviewReport).filter(InterviewReport.session_id == session_id).first()
    if existing is not None and existing.competency_scores is not None:
        # Already generated by this flow — no regeneration (see plan's
        # "prevent duplicate report generation" requirement).
        return existing

    candidate = db.get(Candidate, session.candidate_id)
    job = db.get(Job, session.job_id)

    raw = get_ai_provider().generate_final_report(
        job_description=job.description if job else "",
        required_skills=_format_required_skills(job),
        candidate_profile=_format_candidate_profile(candidate) if candidate else "Not specified",
        candidate_cv=(candidate.cvs[-1].parsed_text if candidate and candidate.cvs else "") or "Not provided",
        questions_and_answers=_format_questions_and_answers(session),
        answer_evaluations=_format_answer_evaluations(db, session.answers),
    )

    try:
        validated = FinalReportLLMResponse.model_validate(raw)
    except ValidationError as exc:
        raise AIResponseError(f"Model returned an invalid report: {exc}") from exc

    report = existing or InterviewReport(session_id=session_id)
    report.summary = validated.summary
    report.recommendation = validated.recommendation
    report.overall_score = validated.overall_score
    report.competency_scores = validated.competency_scores.model_dump()
    report.strengths = validated.strengths
    report.development_areas = validated.development_areas
    report.evidence = [item.model_dump() for item in validated.evidence]
    session.status = "completed"

    db.add(report)
    db.commit()
    db.refresh(report)
    return report
