"""add decision_email_sent_for to interview_reports

Revision ID: 0007e78d97e8
Revises: 4cfe77b40390
Create Date: 2026-08-24 10:44:04.146071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007e78d97e8'
down_revision: Union[str, None] = '4cfe77b40390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_reports', sa.Column('decision_email_sent_for', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_reports', 'decision_email_sent_for')
    # ### end Alembic commands ###
