"""add adaptive interview question fields and ai_evaluations table

Revision ID: 0fe86c0a64d5
Revises: bf44335f17ab
Create Date: 2026-08-08 18:16:46.081198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe86c0a64d5'
down_revision: Union[str, None] = 'bf44335f17ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('competency', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_sufficient', sa.Boolean(), nullable=False),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['candidate_answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.add_column('interview_questions', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('interview_questions', sa.Column('difficulty', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'difficulty')
    op.drop_column('interview_questions', 'category')
    op.drop_table('ai_evaluations')
    # ### end Alembic commands ###
