"""replace magic-link invitations with assigned login_email credentials

Revision ID: 1011a7882442
Revises: 04dc50c5044b
Create Date: 2026-08-12 14:57:15.918818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1011a7882442'
down_revision: Union[str, None] = '04dc50c5044b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_invitations_token', table_name='candidate_invitations')
    op.drop_table('candidate_invitations')
    op.add_column('candidates', sa.Column('login_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_candidates_login_email'), 'candidates', ['login_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_login_email'), table_name='candidates')
    op.drop_column('candidates', 'login_email')
    op.create_table('candidate_invitations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='candidate_invitations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_candidate_invitations_token', 'candidate_invitations', ['token'], unique=True)
    # ### end Alembic commands ###
