"""add feedback column to ai_evaluations

Revision ID: 12663f63091f
Revises: 7089a182702a
Create Date: 2026-08-10 10:18:15.879522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12663f63091f'
down_revision: Union[str, None] = '7089a182702a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_evaluations', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_evaluations', 'feedback')
    # ### end Alembic commands ###
