"""add media metadata columns to candidate_answers

Revision ID: 13f69721eeed
Revises: 12663f63091f
Create Date: 2026-08-10 10:43:30.509838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f69721eeed'
down_revision: Union[str, None] = '12663f63091f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_answers', sa.Column('media_filename', sa.String(length=255), nullable=True))
    op.add_column('candidate_answers', sa.Column('media_content_type', sa.String(length=100), nullable=True))
    op.add_column('candidate_answers', sa.Column('media_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_answers', 'media_size')
    op.drop_column('candidate_answers', 'media_content_type')
    op.drop_column('candidate_answers', 'media_filename')
    # ### end Alembic commands ###
