"""make job_transfer_requests user fks nullable

Revision ID: 210d75f39b50
Revises: 9cba1c8288a3
Create Date: 2026-08-13 16:02:05.212425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '210d75f39b50'
down_revision: Union[str, None] = '9cba1c8288a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_transfer_requests', 'from_user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_transfer_requests', 'to_user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_transfer_requests', 'requested_by_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_transfer_requests', 'requested_by_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_transfer_requests', 'to_user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_transfer_requests', 'from_user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
