"""add final report fields to interview_reports

Revision ID: 3295e1bb73b5
Revises: fd5a2ccfb8eb
Create Date: 2026-08-10 15:53:23.123504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3295e1bb73b5'
down_revision: Union[str, None] = 'fd5a2ccfb8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_reports', sa.Column('overall_score', sa.Integer(), nullable=True))
    op.add_column('interview_reports', sa.Column('competency_scores', sa.JSON(), nullable=True))
    op.add_column('interview_reports', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('interview_reports', sa.Column('development_areas', sa.JSON(), nullable=True))
    op.add_column('interview_reports', sa.Column('evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_reports', 'evidence')
    op.drop_column('interview_reports', 'development_areas')
    op.drop_column('interview_reports', 'strengths')
    op.drop_column('interview_reports', 'competency_scores')
    op.drop_column('interview_reports', 'overall_score')
    # ### end Alembic commands ###
