"""drop candidate login_email and hashed_password

Revision ID: 4cfe77b40390
Revises: 0e7ef3b18d50
Create Date: 2026-08-17 12:40:57.128172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4cfe77b40390'
down_revision: Union[str, None] = '0e7ef3b18d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_login_email', table_name='candidates')
    op.drop_column('candidates', 'login_email')
    op.drop_column('candidates', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('candidates', sa.Column('login_email', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_candidates_login_email', 'candidates', ['login_email'], unique=True)
    # ### end Alembic commands ###
