"""add candidate interview_reset_at

Revision ID: 5a0eba35ea50
Revises: 210d75f39b50
Create Date: 2026-08-17 08:32:30.110135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0eba35ea50'
down_revision: Union[str, None] = '210d75f39b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('interview_reset_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'interview_reset_at')
    # ### end Alembic commands ###
