"""add kvkk consent column

Revision ID: 7089a182702a
Revises: 0fe86c0a64d5
Create Date: 2026-08-10 09:48:20.102986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7089a182702a'
down_revision: Union[str, None] = '0fe86c0a64d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'consent_records',
        sa.Column('kvkk_consent', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('consent_records', 'kvkk_consent', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consent_records', 'kvkk_consent')
    # ### end Alembic commands ###
