"""add candidate password

Revision ID: 7edee66bfb52
Revises: 7f081ba4fb5e
Create Date: 2026-08-05 13:27:40.071076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edee66bfb52'
down_revision: Union[str, None] = '7f081ba4fb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'hashed_password')
    # ### end Alembic commands ###
