"""add cv analysis column

Revision ID: bf44335f17ab
Revises: 7edee66bfb52
Create Date: 2026-08-08 16:02:15.077019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf44335f17ab'
down_revision: Union[str, None] = '7edee66bfb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_cvs', sa.Column('analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_cvs', 'analysis')
    # ### end Alembic commands ###
