"""add hr_decision to interview_reports

Revision ID: cc6689d490d4
Revises: cd9454035c72
Create Date: 2026-08-13 12:15:14.469724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6689d490d4'
down_revision: Union[str, None] = 'cd9454035c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_reports', sa.Column('hr_decision', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_reports', 'hr_decision')
    # ### end Alembic commands ###
