"""add recording offset columns to candidate_answers

Revision ID: ea9344164d0a
Revises: c96f134b379c
Create Date: 2026-08-11 09:13:03.333522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9344164d0a'
down_revision: Union[str, None] = 'c96f134b379c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_answers', sa.Column('recording_start_offset_seconds', sa.Float(), nullable=True))
    op.add_column('candidate_answers', sa.Column('recording_end_offset_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_answers', 'recording_end_offset_seconds')
    op.drop_column('candidate_answers', 'recording_start_offset_seconds')
    # ### end Alembic commands ###
