"""add recording columns to interview_sessions

Revision ID: fd5a2ccfb8eb
Revises: 13f69721eeed
Create Date: 2026-08-10 14:04:14.192233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5a2ccfb8eb'
down_revision: Union[str, None] = '13f69721eeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('recording_path', sa.String(length=500), nullable=True))
    op.add_column('interview_sessions', sa.Column('recording_filename', sa.String(length=255), nullable=True))
    op.add_column('interview_sessions', sa.Column('recording_content_type', sa.String(length=100), nullable=True))
    op.add_column('interview_sessions', sa.Column('recording_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'recording_size')
    op.drop_column('interview_sessions', 'recording_content_type')
    op.drop_column('interview_sessions', 'recording_filename')
    op.drop_column('interview_sessions', 'recording_path')
    # ### end Alembic commands ###
